theme: jekyll-theme-leap-day
title: "Predict the Air Pollution by Geo-locations in Sofia"
description: "Science meets Regions: Energy and Climate Change. Social Effects of Climate Change, 29-31 March 2019"
show_downloads: "true"
